# Generated by Django 3.2.21 on 2023-11-05 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xnetwork_messages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='username1',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chat',
            name='username2',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
    ]
